package io.vigil.common.model;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * One security telemetry event as it flows through the pipeline.
 *
 * <p>This is a record: an immutable value type whose constructor, accessors,
 * equals, hashCode and toString are generated by the compiler. Jackson can
 * serialize and deserialize records without extra annotations because the
 * component names match the JSON field names.
 *
 * @param id              unique id, a UUID; the ingest service assigns one if absent
 * @param timestamp       when the event happened (event time, not arrival time)
 * @param source          source IP or host that produced the activity
 * @param username        account involved, may be null
 * @param eventType       what kind of activity this is
 * @param destination     target host or resource, may be null
 * @param destinationPort target port, may be null
 * @param rawMessage      original log line, may be null
 * @param metadata        open key/value bag for extra fields, may be null
 */
public record SecurityEvent(
        String id,
        Instant timestamp,
        String source,
        String username,
        EventType eventType,
        String destination,
        Integer destinationPort,
        String rawMessage,
        Map<String, String> metadata) {

    /** Returns a copy of this event with a freshly generated id if it has none. */
    public SecurityEvent withGeneratedIdIfMissing() {
        if (id != null && !id.isBlank()) {
            return this;
        }
        return new SecurityEvent(UUID.randomUUID().toString(), timestamp, source, username,
                eventType, destination, destinationPort, rawMessage, metadata);
    }
}
